# -*- coding: utf-8 -*-
"""escolas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9C3-Gkw1EsVRWNpiCeALCkm0E2Lytrk
"""

!pip install geopandas rtree mapclassify geobr

import geopandas as gpd
import rtree
import mapclassify
import geobr

# Abrindo nosso shp
gdf = geobr.read_municipality(code_muni='all', year=2020)
gdf.head()

cal = gdf[gdf.name_muni=='Poços De Caldas']
cal

cal.crs= 'epsg:4674'
cal.crs

cal.explore(
    color= 'gray',
    tooltip = 'name_muni',
    name= 'Poços De Caldas',
    tiles = 'CartoDB positron'

)

gdf_base = geobr.read_schools(year=2020)
gdf_base.head()

gdf_base.crs= 'epsg:4674'
gdf_base.crs

# Juntando as info do poligono de poços com as info das escolas em uma só tabela.
gdf_base_cal = gpd.sjoin(gdf_base, cal)
gdf_base_cal.head()

# Conferindo nome das colunas
gdf_base_cal.columns

# Juntando a vizualização passada com a nova que contém as info escolas

m = cal.explore(
    color= 'gray',
    tooltip = False,

    name= 'Poços De Caldas',
    tiles = 'CartoDB positron'
)

gdf_base_cal.explore(
    m=m,
    column= 'government_level',
    scheme= 'NaturalBreaks',
    cmap= 'Spectral',

    tooltip= False,

    name = 'Escolas',
    style_kwds=dict(color='black', weight=3, opacity= 1),
    popup = ['name_school', 'address', 'government_level', 'phone_number'],
    legend= True,
    legend_kwds=dict(caption= 'Legenda'),
    marker_type= 'circle',
    marker_kwds=dict(radius=30),
    height=800,
    width=800,
)

m

m.save(outfile= 'escolas_cal.html')
# Definindo a saida como HTML